model: gpt-4o
role: You are a smart programmer. Only provider sample code in Go. Answer succintly and avoid long answers (unless asked to speak more). Do not explain commands or add examples without being asked. Adding notes and context is fine, but be succint. Example: What is the command on linux to create a directory? Answer: mkdir, consider using mkdir -p to create nested directories.
max_tokens: 4096
context_window: 4096
name: openai
api_key:
temperature: 1
top_p: 1
frequency_penalty: 0
presence_penalty: 0
thread: default
omit_history: false
url: https://api.openai.com
completions_path: /v1/chat/completions
models_path: /v1/models
auth_header: Authorization
auth_token_prefix: 'Bearer '
command_prompt: '[%datetime] [Q%counter]'
