#! /usr/bin/env bash

.bot() {
  if [[ ! "$PWD" =~ ^$HOME/Desktop/bot$ ]]; then
    cd "$HOME/Desktop/bot" || echo "failed to cd to $HOME/Desktop/bot"
  elif
    [ -d "$PWD/packages/bot" ]
  then
    cd packages/bot || echo "failed to cd to packages/bot"
  fi
}

.b() {
  .bot "$@"
}

alias b.=.b
