$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
allowCompoundWords: true
maxNumberOfProblems: 7
dictionaries:
  - en-US
  - bash
  - docker
  - filetypes
  - fullstack
  - golang
  - k8s
  - lorem-ipsum
  - softwareTerms
  - computing-acronyms
ignorePaths:
  - priv/database.bcup
  - bin/cloud-sql-proxy
  - priv/secureBootKeysZ390M
  - bin/baristai
  - bin/dir-rename
  - bin/filer
  - bin/rename
  - bin/typo
  - dotfiles/lib-git-prompt.sh
  - dotfiles/Brewfile
  - etc
  - LICENSE
words:
  - aliasg
  - alnum
  - argn
  - baristai
  - bcup
  - btrfs
  - cfprefsd
  - commitlintrc
  - coreutils
  - cpio
  - csum
  - dator
  - devmode
  - euox
  - filerrc
  - findutils
  - gcmsg
  - glslang
  - grbonto
  - grepl
  - grepr
  - guake
  - initdb
  - iterm
  - kaue
  - kazuo
  - lemos
  - libavif
  - libheif
  - libmp
  - lzma
  - mackup
  - mkpath
  - msgln
  - nauck
  - ncdu
  - noconfirm
  - pacu
  - pgsql
  - prefs
  - psql
  - tcodes0
  - teramoto
  - thomazella
  - uncompress
  - unlzma
  - unrar
  - unxz
  - vacuumdb
  - wneessen
  - IGPU
  - ZYMA
  - HDAS
  - HDEF
  - HECI
  - IMEI
  - ACPI
  - DSDT
  - HPET
  - IPIC
  - DSDT
  - SEVDSQ
  - FUMA
  - FUQQ
  - GLAN
  - GIGE
  - ASPM
  - DMAR
  - MCFG
  - SSDT
  - APLF
  - APSN
  - busid
  - AQAAAA
  - CQAAAA
  - noatime
  - ucode
  - ppfeaturemask
  - EDID
  - Kext
  - CPUPM
  - XCPM
  - Kexts
  - AHCI
  - Mikey
  - AGDP
  - UAAAA
  - USBXHCIPCI
  - QAAA
  - USBXHCI
  - ydeng
  - iokit
  - IOUSB
  - GULNV
  - ZPJV
  - zswap
  - zram
  - rocm
