#! /usr/bin/env bash

set -euo pipefail
shopt -s globstar
trap 'echo fatal: $0:$LINENO >&2' ERR

cmd="${1:-help}"

push_vllm_amd64() {
  vllmVersion="${1:-}"
  template="${2:-}"

  if [[ -z "$vllmVersion" ]] || [[ -z "$template" ]]; then
    echo "Usage: $0 <vllm_version> <template>"
    echo "Example: $0 v0.27.1 qwen35"
    exit 1
  fi

  version="$(git describe --tags --abbrev=0 --match "vllm/$template/*")"
  version="${version#vllm/"$template"/}"
  commit="$(git rev-parse --short HEAD)"
  date="$(date +%Y.%m.%d.%H:%M)"
  dir="src/vllm/$template"

  docker buildx build --platform linux/amd64 \
    --build-context default="$dir" \
    --build-arg VLLM_VERSION="${vllmVersion}" \
    --build-arg VERSION="${version}_${commit}_$date" \
    -t ghcr.io/rthomazel/interface/vllm/"$template":"$version" \
    -t ghcr.io/rthomazel/interface/vllm/"$template":latest \
    --push "$dir"
}

case "$cmd" in
# -- run shfmt and oxfmt
format)
  find bin dotfiles -type f -print0 |
    xargs -0 grep -lZE '^#! ?/usr/bin/env bash|^#!/usr/bin/env bash|^#! ?/bin/bash' |
    xargs -0 shfmt -i 2 -ln bash -w
  find . -type f \( -iname "*.md" -o -iname "*.json" \) -print0 | xargs -0 oxfmt
  ;;
# -- run shellcheck on all bash scripts
lint)
  find bin dotfiles -type f -print0 |
    xargs -0 grep -lZE '^#! ?/usr/bin/env bash|^#!/usr/bin/env bash|^#! ?/bin/bash' |
    xargs -0 shellcheck -x
  ;;
# -- install required dev tools
setup)
  bin/setup
  ;;
# -- build and push VLLM amd64 docker image with custom entrypoint
vllm:pushImage)
  push_vllm_amd64 "${@:2}"
  ;;
help | *)
  echo "Usage: ./run <command>"
  echo ""
  echo "Commands:"
  awk '/^# -- /{desc=substr($0, index($0,"-- ")+3)} /\)$/ && desc{cmd=$0; gsub(/[[:space:]()|*]/, "", cmd); printf "  %-20s %s\n", cmd, desc; desc=""}' "$0"
  ;;
esac
