#! /usr/bin/env bash
# Copyright 2025-present R. Thomazella. All rights reserved.
# Use of this source code is governed by the BSD-3-Clause
# license that can be found in the LICENSE file and online
# at https://opensource.org/license/BSD-3-clause.
#
# This file is generated by an external script. Avoid edits. 

set -euo pipefail
shopt -s globstar
trap 'echo error: line $LINENO >&2' ERR

